from .data import load_etf_dataframe, build_bt_feed_dataframe
from .custom_strategy_example import example_equal_weight_momentum_signal
from .strategies import (
    BaseFactorTimingStrategy,
    ExampleCustomTimingStrategy,
    FunctionalPortfolioTimingStrategy,
    MinimalFactorTimingStrategyTemplate,
    MultiFactorTimingStrategy,
    NewHighBATRSTimingStrategy,
    WeightSignalFunction,
)
from .engine import (
    PortfolioBacktestConfig,
    PortfolioBacktestResult,
    SingleFactorSingleTargetBacktestConfig,
    SingleFactorSingleTargetBacktestResult,
    run_portfolio_backtest_from_feeds,
    run_single_factor_single_target_backtest,
)
from .timing_batch import PortfolioBatchConfig, run_portfolio_backtest_batch
from .rotation_signal import make_rotation_signal
from .wide_momentum_baseline import (
    BaselineCandidate,
    CandidateFilterSpec,
    PreparedWideMomentumUniverse,
    SymbolBaselineData,
    ThresholdFilter,
    WideMomentumBaselineConfig,
    WideMomentumBaselineResult,
    WideMomentumVariantResult,
    prepare_wide_momentum_universe,
    prepare_wide_momentum_universe_from_frames,
    run_wide_momentum_baseline,
    run_wide_momentum_baseline_from_prepared,
    save_wide_momentum_baseline_result,
)
from .index_rotation import (
    IndexRotationDiscoveryResult,
    KeywordRepresentativeResult,
    build_pairwise_correlation_frame,
    build_representative_etf_frame,
    discover_index_keyword_representatives,
    discover_index_rotation_candidates,
    match_index_keywords,
    search_low_correlation_combos,
    select_keyword_representatives,
)
from .preprocessing import (
    FactorCalcResult,
    LoadFilterResult,
    PreprocessError,
    ensure_output_compatibility,
    parallel_calc_factors_for_map,
    parallel_load_filter_etf_data,
    slice_etf_data_map_by_date_range,
    DateRangeSliceResult,
)
from .summary_compare import (
    ComparisonMetricSpec,
    DEFAULT_METRICS,
    TIMING_SINGLE_FACTOR_DEFAULT_METRICS,
    build_comparison_text_report,
    build_timing_comparison_report,
    compare_summary_dfs,
    compare_timing_summary_dfs,
)

__all__ = [
    "load_etf_dataframe",
    "build_bt_feed_dataframe",
    "example_equal_weight_momentum_signal",
    "BaseFactorTimingStrategy",
    "WeightSignalFunction",
    "FunctionalPortfolioTimingStrategy",
    "ExampleCustomTimingStrategy",
    "MinimalFactorTimingStrategyTemplate",
    "MultiFactorTimingStrategy",
    "NewHighBATRSTimingStrategy",
    "PortfolioBacktestConfig",
    "PortfolioBacktestResult",
    "SingleFactorSingleTargetBacktestConfig",
    "SingleFactorSingleTargetBacktestResult",
    "run_portfolio_backtest_from_feeds",
    "run_single_factor_single_target_backtest",
    "PortfolioBatchConfig",
    "run_portfolio_backtest_batch",
    "make_rotation_signal",
    "BaselineCandidate",
    "CandidateFilterSpec",
    "PreparedWideMomentumUniverse",
    "SymbolBaselineData",
    "ThresholdFilter",
    "WideMomentumBaselineConfig",
    "WideMomentumBaselineResult",
    "WideMomentumVariantResult",
    "prepare_wide_momentum_universe",
    "prepare_wide_momentum_universe_from_frames",
    "run_wide_momentum_baseline",
    "run_wide_momentum_baseline_from_prepared",
    "save_wide_momentum_baseline_result",
    "IndexRotationDiscoveryResult",
    "KeywordRepresentativeResult",
    "build_pairwise_correlation_frame",
    "build_representative_etf_frame",
    "discover_index_keyword_representatives",
    "discover_index_rotation_candidates",
    "match_index_keywords",
    "search_low_correlation_combos",
    "select_keyword_representatives",
    "slice_etf_data_map_by_date_range",
    "DateRangeSliceResult",
    "PreprocessError",
    "LoadFilterResult",
    "FactorCalcResult",
    "parallel_load_filter_etf_data",
    "parallel_calc_factors_for_map",
    "ensure_output_compatibility",
    "ComparisonMetricSpec",
    "TIMING_SINGLE_FACTOR_DEFAULT_METRICS",
    "DEFAULT_METRICS",
    "compare_timing_summary_dfs",
    "compare_summary_dfs",
    "build_timing_comparison_report",
    "build_comparison_text_report",
]
